version: '3'
services:
  api:
    image: node-docker
    build: .
    networks:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
    command: npm run dev

  web-cli:
    image: node-docker
    networks:
      - backend
    command: sh

networks:
  backend:
    driver: bridge
